name: Run Crypto Predictor

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run-predictor:
    runs-on: ubuntu-latest  # Use GitHub's Ubuntu runner

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3  # Fetch the latest code from the repo

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Specify the Python version

    - name: Install Dependencies
      run: pip install -r requirements.txt  # Install the Python dependencies

    - name: Run Prediction Script
      run: python app.py  # Execute your prediction script
