name: Run Crypto Predictor

on:
  workflow_dispatch:  # Allows manual triggering of the workflow
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  deploy:
    runs-on: ubuntu-latest  # GitHub Actions runner

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Debug Installed Packages
      run: pip list  # List installed packages to verify `dotenv` is installed

    - name: Run Predictor Script
      run: python app.py

    - name: Deploy Predictions
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        touch .nojekyll
        git add predictions.json .nojekyll
        git commit -m "Update predictions.json" || echo "No changes to commit"
        git push origin main
