name: Run Crypto Predictor

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC


jobs:
  run-predictor:
    runs-on: ubuntu-latest  # Use GitHub's Ubuntu runner

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3  # Fetch the latest code

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: pip install -r requirements.txt  # Install required Python libraries
    
    - name: Run Predictor Script
      run: python app.py  # Run the script normally; do not redirect output

    - name: Debug Predictions File
      run: |
        echo "Contents of predictions.json:"
        cat predictions.json

    - name: Upload Predictions
      uses: actions/upload-artifact@v3  # Make predictions available for download
      with:
        name: predictions
        path: predictions.json

    - name: Deploy Predictions to GitHub Pages
      run: |
        mkdir -p docs
        cp predictions.json docs/
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add docs/predictions.json
        git commit -m "Update predictions.json"
        git push origin main

        

