name: Run Crypto Predictor

on:
  workflow_dispatch:  # Allows manual triggering of the workflow
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  run-predictor:
    runs-on: ubuntu-latest  # Use GitHub's Ubuntu runner

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3  # Fetch the latest code

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: pip install -r requirements.txt  # Install required Python libraries

    - name: Run Predictor Script
      run: python app.py  # Generate predictions.json

    - name: Debug Predictions File
      run: |
        echo "Contents of predictions.json:"
        cat predictions.json

    - name: Deploy Predictions to GitHub Pages
      env:
        GITHUB_TOKEN: ${{ secrets.Token }}  # Use the secret token
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        mkdir -p docs
        cp predictions.json docs/
        git add docs/predictions.json
        git commit -m "Update predictions.json"
        git push origin main
